name: Metrics
on:
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.base.svg
          base: header, repositories
          plugin_lines: yes
          base_indepth: yes
      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_from: 1000
          plugin_habits_days: 30
          config_timezone: Europe/Paris
      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starred-topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
      - name: Compact display in base plugin
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_history_limit: 5
      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, json, tex, less, dockerfile, makefile, qmake, lex, cmake, shell
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
